### ISSUE TITLE
Says url isn’t valid 

### ISSUE THREAD

**Issue by PartyingChair** [infinitepower18/Homepage-MobileSafari#10]
### Describe the bug

![IMG_4346](https://github.com/user-attachments/assets/313fb001-ca3b-4154-9b27-01c07ed9bf8a)

get error when trying to configure url http://10.52.3.36:3050

### Steps to reproduce

Set url to http://10.52.3.36:3050/ and try to save 

### Expected behavior

URL should save 

### Extension configuration

- [X] The extension is configured correctly

### Device

iPhone

### OS version

18.0

### App version

2.1.0

**Comment by infinitepower18** [comment]
Fixed in v2.1.1. Please update to the latest version.

**Comment by knaz128112** [comment]
accounts.google.com
