### ISSUE TITLE
Not working on latest 18.1 beta

### ISSUE THREAD

**Issue by yihuanlin** [infinitepower18/Homepage-MobileSafari#8]
### Describe the bug

Worked well on previous betas of iOS 18.1 but not on the latest one

### Steps to reproduce

Config the app. Open a new tab

### Expected behavior

The default new tab instead of my custom one show up

### Device

iPhone

### OS version

18.1

### App version

Latest release

**Comment by infinitepower18** [comment]
Have you checked the "Open New Tabs" setting? And by the latest beta, do you mean iOS 18.1 beta 3?

![image](https://github.com/user-attachments/assets/44a486c9-6f8b-45f2-9b61-71c01c37e806)

**Comment by infinitepower18** [comment]
> idk why it need to be redone after a system update tho

It's most likely an iOS bug.

**Comment by dennisdebel** [comment]
It seems to revert back to ‘Start Page’ after running the Shortcut to set the new ‘Home page’ url!

**Comment by infinitepower18** [comment]
> It seems to revert back to ‘Start Page’ after running the Shortcut to set the new ‘Home page’ url!

The app has no control over that setting at all. Under Settings -> Apps -> Safari -> Extensions -> Homepage is Open New Tabs set to Homepage or Start Page?
